### ISSUE TITLE
some file is 404: Not Found.

### ISSUE THREAD

**Issue by wayyoungboy** [traas-stack/chaosmeta#20]
![image](https://github.com/traas-stack/chaosmeta/assets/35394786/5c93d1ee-0521-412b-ae45-94277d629b05)

**Comment by KingsonKai** [comment]
Thanks for your feedback, the document description is wrong (the version of the command should be "v0.1.0" instead of "0.1.0"), it has been fixed now, please revisit the document and refresh it: https://chaosmeta.gitbook .io/chaosmeta-cn/an-zhuang-zhi-yin/jiao-ben-an-zhuang
