### ISSUE TITLE
Add `golangci-lint` check in CI

### ISSUE THREAD

**Issue by chunshao90** [traas-stack/chaosmeta#32]
Add `golangci-lint` check in CI.

**Comment by KingsonKai** [comment]
Ok, I will consider adding it later. However, if you are willing to submit a PR to add it is also very welcome

**Comment by chunshao90** [comment]
Is there anyone developing and maintaining this repository?

**Comment by KingsonKai** [comment]
Now I am continuing to develop and maintain this repository, the current version is indeed not perfect, but we are still improving
