### ISSUE TITLE
关于度量引擎和流量注入

### ISSUE THREAD

**Issue by myl1019** [traas-stack/chaosmeta#62]
hi~
我使用0.5.0版本部署文件部署了chaosmeta体验一下，发现度量引擎和流量注入是被禁用的，是我的配置不对还是还没有release出来呢

**Comment by KingsonKai** [comment]
当前版本，用户界面中还没接通度量引擎和流量注入的能力
只提供了对应的operator，需要通过创建对应的CR来触发
我们会尽快在下个版本就接到用户界面中

**Comment by KingsonKai** [comment]
support in v0.6.0
