### ISSUE TITLE
前端bug：编辑实验时，无法带入原来的”Kubernetes Label“

### ISSUE THREAD

**Issue by cycwll** [traas-stack/chaosmeta#69]
如下截图，原来我这里配置的Kubernetes Label 是 app=httpserver。但当我编辑这个实验的时候，这里显示空的，并没有把本来设置的值带过来。
<img width="306" alt="image" src="https://github.com/traas-stack/chaosmeta/assets/6410130/e19aaeed-c286-4a96-8822-6f3cfa28d2e8">

**Comment by KingsonKai** [comment]
fix in v0.5.2
