### ISSUE TITLE
"parallel" or "serial" experiments, but the actual results are opposite

### ISSUE THREAD

**Issue by cycwll** [traas-stack/chaosmeta#70]
When I create a “parallel” experiment, it is actually executed serially. When I create a “serial” experiment, it is actually executed in parallel.
The following screenshot shows that the two experiments in row “1” are actually executed in parallel, while the experiment in row "2" is executed after the experiment in row 1 is completed.
<img width="533" alt="image" src="https://github.com/traas-stack/chaosmeta/assets/6410130/0fe1f6d5-e866-48ca-af1a-ff8f93b2f3cd">

**Comment by KingsonKai** [comment]
fix in v0.5.2
