### ISSUE TITLE
Bug:  Unable to perform memory fill by "bytes"

### ISSUE THREAD

**Issue by cycwll** [traas-stack/chaosmeta#84]
pod-->mem --> fill
Due to the limitations on the front end of the page, percentage is required and must be between 1 and 100, and cannot be 0. And once percent= 0, the number of injected bytes will be calculated based on percentage (source code chaosmetad pkg/utils/memory/mem. go). This results in the inability to specify a fixed byte value。

由于页面前端限制了 percent 为必填项，并且必须为1-100之间，不能为0。一旦 percent !=0 ，就会按percent计算注入的bytes数，（源码chaosmetad pkg/utils/memory/mem.go 34行）。从而导致无法指定一个固定的 bytes 值，或者说指定了也无效，因为percent不能填0。

<img width="223" alt="image" src="https://github.com/traas-stack/chaosmeta/assets/6410130/9882c26d-e2a6-423e-9ba5-269868e3da17">

_另外，我个人觉得对于pod来说，这里的 percent 没什么实际意义，因为percent是按宿主机的内存指标计算的，与pod的request和limit都没有关系。这里的逻辑是否应该完善一下？不知道我的理解是否正确，还是这个设计是针对某特定场景而考虑的。_

**Comment by KingsonKai** [comment]
fix in v0.6.0
